# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 03:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('localidades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('distribuidoras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distribuidora_Solicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distribuidora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distribuidoras.Distribuidora')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(max_length=50)),
                ('dni', models.BigIntegerField()),
                ('telefono', models.BigIntegerField(blank=True)),
                ('celular', models.BigIntegerField(blank=True)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('numero_contacto', models.BigIntegerField()),
                ('direccion', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('p', 'Pendiente'), ('a', 'Activo')], max_length=1)),
                ('localidad', models.ForeignKey(default=3935, on_delete=django.db.models.deletion.CASCADE, to='localidades.Localidad')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='distribuidora_solicitud',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitudes.Solicitud'),
        ),
    ]
