# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 18:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localidades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='id_provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localidades.Provincia', verbose_name='Provincia'),
        ),
        migrations.AlterField(
            model_name='localidad',
            name='codigo_postal',
            field=models.CharField(max_length=10, verbose_name='Codigo postal'),
        ),
        migrations.AlterField(
            model_name='localidad',
            name='id_departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localidades.Departamento', verbose_name='Departamento'),
        ),
    ]
