# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 03:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presentacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacidad', models.CharField(max_length=50)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripsiom', models.TextField()),
                ('precio_unitario', models.FloatField()),
                ('estado', models.BooleanField(default=True)),
                ('marcaSubCategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categorias.Marca_SubCategoria')),
                ('presentacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.Presentacion')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.Tipo_Producto'),
        ),
    ]
