# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 20:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distribuidoras', '0002_auto_20170131_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='estado',
            field=models.CharField(choices=[(b'l', b'Listo'), (b'v', b'vigente'), (b'f', b'finalizado')], max_length=1),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='fecha_fin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='fecha_inicio',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='distribuidora',
            name='descripcion',
            field=models.TextField(verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='distribuidora',
            name='direccion',
            field=models.CharField(max_length=50, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='distribuidora',
            name='id_localidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localidades.Localidad', verbose_name='Localidad'),
        ),
        migrations.AlterField(
            model_name='distribuidora',
            name='numero_contacto',
            field=models.PositiveIntegerField(verbose_name='Numero de contacto'),
        ),
        migrations.AlterField(
            model_name='distribuidora',
            name='persona_cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Persona a cargo'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='dia',
            field=models.CharField(choices=[(b'lu', b'Lunes'), (b'ma', b'Martes'), (b'mi', b'Miercoles'), (b'ju', b'Jueves'), (b'vi', b'Viernes'), (b'sa', b'Sabado'), (b'do', b'Domingo')], max_length=2),
        ),
        migrations.AlterField(
            model_name='usuario_distribuidora',
            name='id_distribuidora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distribuidoras.Distribuidora', verbose_name='Distribuidora'),
        ),
        migrations.AlterField(
            model_name='usuario_distribuidora',
            name='id_permiso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distribuidoras.Permiso_Distribuidora', verbose_name='Permiso'),
        ),
        migrations.AlterField(
            model_name='usuario_distribuidora',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
